# Gradle Properties
org.gradle.jvmargs=-Xmx12G -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.daemon=false
org.gradle.parallel=true
android.enableBuildCache=true
org.gradle.caching=true

# Project Details
jvm_version=8

project_group=de.florianreuth
project_name=AsmFabricLoader
project_version=2.2.2-SNAPSHOT
project_description=A series of cursed Fabric hacks and utilities that break everything.

publish_owner_id=florianreuth
publish_owner_name=Florian Reuth
publish_owner_mail=git@florianreuth.de

supported_minecraft_versions=*
